name: 'Update Lockfile Action'
description: 'Updates the PNPM Lockfile'

runs:
  using: 'composite'
  steps:
    - name: 'Setup'
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: 'Update Lockfile'
      run: pnpm i --lockfile-only

    - name: 'Commit New Lockfile'
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git add pnpm-lock.yaml
        git commit -m "Update pnpm-lock.yaml"
        git push
