export type { EqualityInteger } from './EqualityInteger'
export type { ComparisonOperator } from './ComparisonOperator'
export type { OperatorToEqualityInteger } from './OperatorToEqualityInteger'
export type { Versioning } from './Versioning'
export type { Wildcard } from './Wildcard'
