name: 'Build And Test'

on:
  - pull_request
  - workflow_call

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run build'
        run: pnpm build

  pretty-check:
    name: 'Pretty Test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run pretty check'
        run: pnpm run pretty:check

  types-test:
    name: 'Types Test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run test types'
        run: pnpm run test:types

  unit-test:
    name: 'Unit Test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run test unit'
        run: pnpm run test:unit --ci

  lint-test:
    name: 'Lint Test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run lint check'
        run: pnpm run lint:check
