name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Dependencies
      uses: jaid/action-npm-install@v1.2.1
#    - run: npm test
