name: 'Dependabot Auto-Merge'

on:
  pull_request:
    branches:
      - 'dependabot/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    name: 'Update Lockfile'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 'Setup'
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 'Update Lockfile'
        run: pnpm i --lockfile-only

      - name: 'Commit New Lockfile'
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add pnpm-lock.yaml
          git commit -m "Update pnpm-lock.yaml"
          git push

  call-test-workflow:
    name: 'Test Workflow Job'
    needs: update-lockfile
    uses: ./.github/workflows/test.yml

  dependabot:
    name: 'Dependabot Job'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: call-test-workflow
    steps:
      - name: 'Dependabot Metadata'
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Enable auto-merge for Dependabot PRs'
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
