name: 'Generate Documentation Workflow'

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    name: "Test Workflow"
    uses: ./.github/workflows/test.yml

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - name: Echo success
        run: echo "success!!"
