name: 'Generate Documentation Workflow'

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    name: 'Test Workflow Job'
    uses: ./.github/workflows/test.yml

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run Typedoc'
        run: pnpm run docs

      # - name: 'Tar Docs'
      #   run: tar -czvf docs.tar.gz docs

      - name: 'Upload Github Pages Artifact'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
          if-no-files-found: error

  deploy:
    name: 'Deploy Documentation Job'
    runs-on: ubuntu-latest
    needs: generate-documentation

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy to GitHub Pages'
        uses: actions/deploy-pages@v1
