name: 'Generate Documentation Workflow'

on:
  push:
    branches:
      - main

jobs:
  call-install-dependencies-action:
    name: 'Install Dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

  call-test-workflow:
    uses: ./.github/workflows/test.yml
    needs: call-install-dependencies-action

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - name: Echo success
        run: echo "success!!"
