name: 'Generate Documentation Workflow'
description: 'Generates documentation for the compare-versions'

on:
  push:
    branches:
      - main

jobs:
  call-install-dependencies:
    uses: ./.github/actions/install-dependencies.yml@v1

  # call-test:
  #   uses: ./.github/workflows/test.yml
  #   needs: call-install-dependencies

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-install-dependencies
    steps:
      - name: Echo success
        run: echo "success!!"
