name: 'Generate Documentation Workflow'

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    name: 'Test Workflow'
    uses: ./.github/workflows/test.yml

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run Typedoc'
        run: pnpm run docs

      - name: 'Deploy Documentation'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
