name: 'Generate Documentation Workflow'
# description: 'Generates documentation for the compare-versions'

on:
  push:
    branches:
      - main

jobs:
  call-install-dependencies-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

  # call-test:
  #   uses: ./.github/workflows/test.yml
  #   needs: call-install-dependencies

  generate-documentation:
    name: 'Generate Documentation Job'
    runs-on: ubuntu-latest
    needs: call-install-dependencies-action
    steps:
      - name: Echo success
        run: echo "success!!"
