name: 'Publish Package Workflow'

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-build-workflow:
    name: 'Build'
    uses: ./.github/workflows/build.yml

  call-test-workflow:
    name: 'Test'
    uses: ./.github/workflows/test.yml

  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: [call-build-workflow, call-test-workflow]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies'
        uses: ./.github/actions/install-dependencies

      - name: 'Download Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-dist
          path: ./dist

      - name: 'Display Structure of Downloaded Files'
        run: ls -R
        working-directory: ./dist

      - name: Publish Package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
