name: 'Test Workflow'

on:
  - workflow_call

jobs:
  pretty-check:
    name: 'Pretty Test Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run pretty check'
        run: pnpm run pretty:check

  types-test:
    name: 'Types Test Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run test types'
        run: pnpm run test:types

  unit-test:
    name: 'Unit Test Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run test unit'
        run: pnpm run test:unit

  lint-test:
    name: 'Lint Test Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install Dependencies Action'
        uses: ./.github/actions/install-dependencies

      - name: 'Run lint check'
        run: pnpm run lint:check
